spring:
  application:
    # 应用名称
    name: @artifactId@
  profiles:
    active: @active@
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /

# Mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.twelvet.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
